#!/usr/bin/env python3
"""Keep the Claude Code and Codex copies of the shared agent tooling in step.

This project is developed with both Claude Code and ChatGPT's Codex, and the
two look for the same kinds of thing in different places. Each resource has
one source of truth, and this script derives the other agent's copy from it:

  source                          derived copy
  ------------------------------  ------------------------------------------
  .agents/skills/<name>/          .claude/skills/<name>/  (byte-for-byte)
  .agents/skills/<name>/SKILL.md  .agents/skills/<name>/agents/openai.yaml
    with disable-model-invocation   (Codex's "explicit invocation only")
  .claude/agents/<name>.md        .codex/agents/<name>.toml
  .claude/agents/<name>.md        .claude/agents/<name>-<effort>.md
    with effort-variants: <levels>  (one per level; see sync_effort_variants)
  .mcp.json                       .codex/config.toml  ([mcp_servers.*])

Skills live under `.agents/skills/` because that is the cross-agent location
(Codex, Cursor, Copilot and others scan it); Claude Code scans only
`.claude/skills/`, so it gets the mirror. Skills that only work under Claude
Code's orchestration (`CLAUDE_ONLY_SKILLS`) stay in `.claude/skills/` and are
not mirrored. The hook manifest `.codex/hooks.json` is small and hand-written;
`tests/test_agent_tooling_sync.py` checks it points at the same dispatcher.

    py -3 tools/sync_agent_tooling.py          # rewrite every derived copy
    py -3 tools/sync_agent_tooling.py --check  # exit 1 and list any drift

Never edit a derived copy by hand: the next sync overwrites it, and the test
fails on it until then.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED_SKILLS = ROOT / ".agents" / "skills"
CLAUDE_SKILLS = ROOT / ".claude" / "skills"
CLAUDE_AGENTS = ROOT / ".claude" / "agents"
CODEX_AGENTS = ROOT / ".codex" / "agents"
MCP_JSON = ROOT / ".mcp.json"
CODEX_CONFIG = ROOT / ".codex" / "config.toml"

#: Skills that drive Claude Code's own subagents and Workflow tool, with
#: scripts other files call by their `.claude/skills/...` path. They are not
#: portable, so they stay where they are and are left out of the mirror.
CLAUDE_ONLY_SKILLS = {"workorder"}

#: Claude Code `effort:` -> Codex `model_reasoning_effort`. Codex has no `max`.
EFFORT = {"low": "low", "medium": "medium", "high": "high", "xhigh": "xhigh", "max": "xhigh"}
#: Fallback for a Haiku agent with no `effort:` (every one pins one since
#: Haiku 5.5, which honours it): its point is to be cheap, so its Codex twin
#: asks for low effort rather than inheriting the parent's.
TIER_DEFAULT_EFFORT = {"haiku": "low"}
#: Claude tools that write. An agent with none of these is read-only in Codex.
WRITE_TOOLS = {"Edit", "Write", "NotebookEdit"}

GENERATED = "Generated by tools/sync_agent_tooling.py from {source}. Do not edit; edit the source and re-run it."


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """(fields, body) of a `---`-fenced Markdown file. Flat `key: value` only,
    which is all the agent and skill definitions here use."""
    text = text.replace("\r\n", "\n")
    match = re.match(r"---\n(.*?)\n---\n?(.*)\Z", text, re.S)
    if not match:
        raise ValueError("no frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).split("\n"):
        key, sep, value = line.partition(":")
        if sep and key.strip() and not line.startswith((" ", "\t")):
            value = value.strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            fields[key.strip()] = value
    return fields, match.group(2)


def toml_str(value: str) -> str:
    """A TOML basic string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return f'"{escaped}"'


def toml_multiline(value: str) -> str:
    """A TOML multi-line basic string that round-trips `value` exactly."""
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return f'"""\n{escaped}"""'


# --------------------------------------------------------------------- skills

def shared_skill_names() -> list[str]:
    return sorted(p.name for p in SHARED_SKILLS.iterdir() if not p.name.startswith("."))


def openai_yaml_for(skill_dir: Path) -> str | None:
    """Codex's opt-out of implicit invocation, for a skill Claude may only run
    when a person asks for it."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.is_file():
        return None
    fields, _ = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
    if fields.get("disable-model-invocation", "").lower() != "true":
        return None
    return (
        f"# {GENERATED.format(source=f'.agents/skills/{skill_dir.name}/SKILL.md')}\n"
        "# `disable-model-invocation: true` there; this is Codex's equivalent.\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def _tree_differs(a: Path, b: Path) -> list[str]:
    """Relative paths that differ between two trees (missing either side, or
    different bytes)."""
    if a.is_file() or b.is_file():
        return [] if a.is_file() and b.is_file() and filecmp.cmp(a, b, shallow=False) else [a.name]
    if not b.is_dir():
        return ["(missing)"]
    cmp = filecmp.dircmp(a, b, ignore=["__pycache__"])
    out = [f"only in source: {n}" for n in cmp.left_only] + [f"only in mirror: {n}" for n in cmp.right_only]
    _, mismatch, errors = filecmp.cmpfiles(a, b, cmp.common_files, shallow=False)
    out += [f"differs: {n}" for n in mismatch + errors]
    for sub in cmp.common_dirs:
        out += [f"{sub}/{d}" for d in _tree_differs(a / sub, b / sub)]
    return out


def sync_skills(check: bool) -> list[str]:
    problems: list[str] = []
    names = shared_skill_names()
    overlap = CLAUDE_ONLY_SKILLS & set(names)
    if overlap:
        problems.append(f".agents/skills: {sorted(overlap)} are Claude-only and must not be shared")

    for name in names:
        src = SHARED_SKILLS / name
        if src.is_dir():
            wanted = openai_yaml_for(src)
            yaml_path = src / "agents" / "openai.yaml"
            have = yaml_path.read_text(encoding="utf-8").replace("\r\n", "\n") if yaml_path.is_file() else None
            # A hand-written openai.yaml on a skill that needs none is left alone.
            hand_written = have is not None and not have.startswith("# Generated")
            if wanted != have and not (wanted is None and hand_written):
                if check:
                    problems.append(f"{yaml_path.relative_to(ROOT).as_posix()} is out of date")
                elif wanted is None:
                    yaml_path.unlink()
                    if not any(yaml_path.parent.iterdir()):
                        yaml_path.parent.rmdir()
                else:
                    yaml_path.parent.mkdir(parents=True, exist_ok=True)
                    yaml_path.write_text(wanted, encoding="utf-8", newline="\n")

        dst = CLAUDE_SKILLS / name
        diff = _tree_differs(src, dst) if dst.exists() else ["(missing)"]
        if diff:
            if check:
                problems.append(f".claude/skills/{name} differs from .agents/skills/{name}: {', '.join(diff[:5])}")
            else:
                if dst.is_dir():
                    shutil.rmtree(dst)
                elif dst.exists():
                    dst.unlink()
                if src.is_dir():
                    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__"))
                else:
                    shutil.copy2(src, dst)

    for stale in sorted(p for p in CLAUDE_SKILLS.iterdir() if p.name not in names and p.name not in CLAUDE_ONLY_SKILLS):
        if check:
            problems.append(f".claude/skills/{stale.name} has no source in .agents/skills (move it there, or add it to CLAUDE_ONLY_SKILLS)")
        # Not deleted automatically: it may be a skill someone just added in
        # the wrong place, and deleting it would lose their work.
    return problems


# ------------------------------------------------------------ effort variants

#: The Agent tool takes a `model` per call but no `effort`, and whether a
#: Workflow `agent()` call's `effort` beats the agent's own pinned one is not
#: documented. So an agent that /workorder runs at more than one effort lists
#: them in its frontmatter (`effort-variants: medium, xhigh`), and this script
#: writes one `.claude/agents/<name>-<effort>.md` per level: the same body
#: under its own name, with that `effort:`. Spawning `planner-xhigh` then
#: means the same thing on every route, and the effort is readable off the
#: agent type in a transcript, which records no effort of its own.
VARIANT_MARKER = "# Generated by tools/sync_agent_tooling.py"
VARIANT_FIELD = "effort-variants"


def is_generated_variant(path: Path) -> bool:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    return text.startswith(f"---\n{VARIANT_MARKER}")


def variant_levels(fields: dict[str, str]) -> list[str]:
    levels = [v.strip() for v in fields.get(VARIANT_FIELD, "").split(",") if v.strip()]
    for level in levels:
        if level not in EFFORT:
            raise ValueError(f"{fields.get('name')}: effort variant {level!r} is not one of {sorted(EFFORT)}")
        if level == fields.get("effort"):
            raise ValueError(f"{fields.get('name')}: effort variant {level!r} is its own pinned effort")
    return levels


def effort_variant_md(md_path: Path, level: str) -> str:
    """The `<name>-<level>` copy of one source agent: frontmatter lines kept in
    order, with `name`, `effort` and `description` rewritten and the variant
    list dropped; the body byte-for-byte."""
    text = md_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    match = re.match(r"---\n(.*?)\n---\n(.*)\Z", text, re.S)
    if not match:
        raise ValueError(f"{md_path.name}: no frontmatter")
    fields, _ = parse_frontmatter(text)
    base = fields["name"]
    out = [f"{VARIANT_MARKER} from .claude/agents/{md_path.name}. Do not edit; edit the source and re-run it."]
    for line in match.group(1).split("\n"):
        key = line.partition(":")[0].strip() if not line.startswith((" ", "\t")) else ""
        if key == VARIANT_FIELD:
            continue
        if key == "name":
            line = f"name: {base}-{level}"
        elif key == "effort":
            line = f"effort: {level}"
        elif key == "description":
            desc = f"`{base}` at {level} effort. Spawn it only where /workorder's tier tables name `{base}-{level}`. " + fields["description"]
            line = "description: " + json.dumps(desc, ensure_ascii=False)
        out.append(line)
    if "effort" not in fields:
        out.append(f"effort: {level}")
    return "---\n" + "\n".join(out) + "\n---\n" + match.group(2)


def sync_effort_variants(check: bool) -> list[str]:
    problems: list[str] = []
    wanted: dict[str, str] = {}
    for path in sorted(CLAUDE_AGENTS.glob("*.md")):
        if is_generated_variant(path):
            continue
        fields, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
        for level in variant_levels(fields):
            wanted[f"{fields['name']}-{level}.md"] = effort_variant_md(path, level)
    for name, text in wanted.items():
        path = CLAUDE_AGENTS / name
        if path.is_file() and not is_generated_variant(path):
            problems.append(f".claude/agents/{name} is hand-written but collides with a generated effort variant")
            continue
        have = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None
        if have != text:
            if check:
                problems.append(f".claude/agents/{name} is out of date with its source's `{VARIANT_FIELD}`")
            else:
                path.write_text(text, encoding="utf-8", newline="\n")
    for stale in sorted(p for p in CLAUDE_AGENTS.glob("*.md") if p.name not in wanted and is_generated_variant(p)):
        if check:
            problems.append(f".claude/agents/{stale.name} is a generated effort variant no source lists any more")
        else:
            stale.unlink()
    return problems


# --------------------------------------------------------------------- agents

def codex_agent_toml(md_path: Path) -> str:
    fields, body = parse_frontmatter(md_path.read_text(encoding="utf-8"))
    name = fields["name"]
    tools = {t.strip() for t in fields.get("tools", "").split(",") if t.strip()}
    effort = EFFORT.get(fields.get("effort", "")) or TIER_DEFAULT_EFFORT.get(fields.get("model", ""))
    source = f".claude/agents/{md_path.name}"
    preamble = (
        f"This agent is shared with Claude Code; its definition is {source}. "
        "Tool names below are Claude Code's: read Read/Grep/Glob as reading and searching files "
        "(shell commands are fine), Edit/Write as apply_patch, Bash/PowerShell as the shell, and "
        "mcp__<server>__<tool> as that MCP server's tool."
        + (" You are read-only: change no file." if not tools & WRITE_TOOLS else "")
        + "\n\n"
    )
    lines = [
        f"# {GENERATED.format(source=source)}",
        f"# Claude Code tier: model={fields.get('model', '(inherit)')}, effort={fields.get('effort', '(none)')}.",
        f"name = {toml_str(name)}",
        f"description = {toml_str(fields['description'])}",
    ]
    if effort:
        lines.append(f"model_reasoning_effort = {toml_str(effort)}")
    lines.append(f"sandbox_mode = {toml_str('workspace-write' if tools & WRITE_TOOLS else 'read-only')}")
    lines.append(f"developer_instructions = {toml_multiline(preamble + body.lstrip())}")
    return "\n".join(lines) + "\n"


def sync_agents(check: bool) -> list[str]:
    problems: list[str] = []
    wanted = {p.stem + ".toml": codex_agent_toml(p) for p in sorted(CLAUDE_AGENTS.glob("*.md"))}
    if not check:
        CODEX_AGENTS.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in CODEX_AGENTS.glob("*.toml")} if CODEX_AGENTS.is_dir() else set()
    for name, text in wanted.items():
        path = CODEX_AGENTS / name
        have = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None
        if have != text:
            if check:
                problems.append(f".codex/agents/{name} is out of date with .claude/agents/{name[:-5]}.md")
            else:
                path.write_text(text, encoding="utf-8", newline="\n")
    for stale in sorted(existing - wanted.keys()):
        if check:
            problems.append(f".codex/agents/{stale} has no .claude/agents source")
        else:
            (CODEX_AGENTS / stale).unlink()
    return problems


# ------------------------------------------------------------------------ mcp

_ENV_REF = re.compile(r"^\$\{(\w+)\}$")


def codex_config_toml() -> str:
    servers = json.loads(MCP_JSON.read_text(encoding="utf-8"))["mcpServers"]
    out = [f"# {GENERATED.format(source='.mcp.json')}", "# Codex reads this only once the project is trusted.", ""]
    for name, spec in servers.items():
        out.append(f"[mcp_servers.{name}]")
        kind = spec.get("type", "stdio")
        if kind == "stdio":
            out.append(f"command = {toml_str(spec['command'])}")
            if spec.get("args"):
                out.append("args = [" + ", ".join(toml_str(a) for a in spec["args"]) + "]")
            env = spec.get("env") or {}
            unknown = set(spec) - {"type", "command", "args", "env"}
        elif kind == "http":
            out.append(f"url = {toml_str(spec['url'])}")
            env = {}
            headers = dict(spec.get("headers") or {})
            auth = headers.pop("Authorization", None)
            if auth:
                scheme, _, token = auth.partition(" ")
                ref = _ENV_REF.match(token)
                if scheme != "Bearer" or not ref:
                    raise ValueError(f"{name}: only 'Bearer ${{VAR}}' authorization is translatable")
                out.append(f"bearer_token_env_var = {toml_str(ref.group(1))}")
            if headers:
                raise ValueError(f"{name}: headers {sorted(headers)} have no Codex translation here")
            unknown = set(spec) - {"type", "url", "headers"}
        else:
            raise ValueError(f"{name}: MCP transport {kind!r} is not translated")
        if unknown:
            raise ValueError(f"{name}: keys {sorted(unknown)} are not translated; extend codex_config_toml")
        # `KEY: "${KEY}"` means "pass my variable through". Claude Code expands
        # it; Codex forwards only what `env_vars` names, and would otherwise
        # hand the server the literal text `${KEY}`.
        passthrough = [k for k, v in env.items() if (m := _ENV_REF.match(v)) and m.group(1) == k]
        if passthrough:
            out.append("env_vars = [" + ", ".join(toml_str(k) for k in passthrough) + "]")
        env = {k: v for k, v in env.items() if k not in passthrough}
        if any("${" in v for v in env.values()):
            raise ValueError(f"{name}: only same-name ${{VAR}} passthrough is translatable in env")
        if env:
            out.append("")
            out.append(f"[mcp_servers.{name}.env]")
            out += [f"{k} = {toml_str(v)}" for k, v in env.items()]
        out.append("")
    return "\n".join(out)


def sync_mcp(check: bool) -> list[str]:
    text = codex_config_toml()
    have = CODEX_CONFIG.read_text(encoding="utf-8").replace("\r\n", "\n") if CODEX_CONFIG.is_file() else None
    if have == text:
        return []
    if check:
        return [".codex/config.toml is out of date with .mcp.json"]
    CODEX_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CODEX_CONFIG.write_text(text, encoding="utf-8", newline="\n")
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="report drift instead of fixing it")
    args = parser.parse_args(argv)
    # Variants first: they are agents too, and get a Codex copy like any other.
    problems = sync_skills(args.check) + sync_effort_variants(args.check) + sync_agents(args.check) + sync_mcp(args.check)
    for problem in problems:
        print(problem)
    if problems and args.check:
        print("\nRun `py -3 tools/sync_agent_tooling.py` to regenerate the derived copies.")
        return 1
    if problems:
        return 1
    if not args.check:
        print("Agent tooling in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
